<?php include 'nav.phtml'; ?>

<div class="container w-25 mt-5">
<div class="card">
   <div class="card-header gradient text-light">
      <h3>Editar contato</h3>
   </div>
   <div class="card-body">
      <div class="row">
         <div class="col">
            <form action="/editar_contato" method="post">

               <?php foreach ($this->view->contatos as $key => $contato) { ?>
               <div class="form-group">
                  <input type="hidden" name="id" value="<?= $contato['co_id'] ?>">
                  <input name="nome" type="text" class="form-control" value="<?= $contato['co_name'] ?>" placeholder="Nome" required="">
               </div>
               <div class="form-group">
                  <input name="telefone" type="number" value="<?= $contato['co_cellphone'] ?>" class="form-control" placeholder="Telefone" required="">
               </div>
               <div class="form-group">
                  <input name="email" type="email" value="<?= $contato['co_email'] ?>" class="form-control" placeholder="Email" required="">
               </div>
               <div class="form-group">
                  <select name="cidade" class="form-control">
                     <option value="<?= $contatos['co_city'] ?>"><?= $contato['co_city'] ?></option>
                     <option value="brasilia">Brasília</option>
                     <option value="taguatinga">Taguatinga</option>
                     <option value="aguas">Águas Claras</option>
                     <option value="gama">Gama</option>
                  </select>
               </div>
               <div class="form-group">
                  <input name="cep" type="number" value="<?= $contato['co_cep'] ?>" class="form-control" placeholder="CEP" required="">
               </div>
               <div class="row mt-5">
                  <div class="col-6">
                     <a  href="/contatos" class="btn btn-secondary text-light btn-block">Cancelar</a>
                  </div>
                  <div class="col-6">
                     <button class="btn btn-block red" type="submit">Editar</button>
                  </div>
               </div>
            <?php  } ?>
            </form>
         </div>
      </div>
   </div>
</div>