<div class="container">
<div class="d-flex justify-content-center mt-5">
   <div class="card" style="width: 36rem;">
      <div class="card-body">
         <div class="d-flex justify-content-center">
            <img src="/img/logo.png" width="100" />
         </div>
         <div class="row">
            <div class="col">
               <h2>Crie sua conta</h2>
            </div>
         </div>

         <div class="row">
            <div class="col">
               <form action="/cadastrar" method="post">
                  <div class="form-group">
                     <input type="text" name="nome" class="form-control" placeholder="Nome">
                  </div>
                  <div class="form-group">
                     <input type="password" name="senha" class="form-control" placeholder="Senha">
                  </div>
                  <button type="submit" class="btn red btn-block">Cadastrar</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>